In [1]:
# =========================================
# 1. Import the numpy package under the name np.
# =========================================
import numpy as np

In [2]:
# =========================================
# 2. Print the numpy version and the configuration.
# =========================================
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

In [3]:
# =========================================
# 3. Create a null vector of size 10.
# =========================================
print("\n3번")
v = np.zeros(10)
print(v)


3번
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# =========================================
# 4. Create a null vector of size 10 but the fifth value which is 1.
# =========================================
print("\n4번")
v = np.zeros(10)
v[4] = 1
print(v)


4번
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
# =========================================
# 5. Create a vector with values ranging from 10 to 49.
# =========================================
print("\n5번")
v = np.arange(10, 50)
print(v)


5번
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# =========================================
# 6. Reverse a vector (first element becomes last).
# =========================================
print("\n6번")
v = np.arange(10)
print(v[::-1])


6번
[9 8 7 6 5 4 3 2 1 0]


In [7]:
# =========================================
# 7. Create a 3x3 matrix with values ranging from 0 to 8.
# =========================================
print("\n7번")
m = np.arange(9).reshape(3,3)
print(m)


7번
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# =========================================
# 8. Find indices of non-zero elements from [1,2,0,0,4,0].
# =========================================
print("\n8번")
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))


8번
(array([0, 1, 4]),)


In [9]:
# =========================================
# 9. Create a 3x3 identity matrix.
# =========================================
print("\n9번")
print(np.eye(3))


9번
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# =========================================
# 10. Create a 3x3x3 array with random values.
# =========================================
print("\n10번")
print(np.random.random((3,3,3)))



10번
[[[0.84630824 0.30674293 0.82752914]
  [0.86506866 0.21681717 0.89113257]
  [0.74446071 0.49697244 0.09442358]]

 [[0.65034295 0.63921919 0.45175515]
  [0.89903575 0.14629198 0.77481623]
  [0.28360075 0.87369394 0.36446667]]

 [[0.2244107  0.6202625  0.46662549]
  [0.58227414 0.49086142 0.47846629]
  [0.58796102 0.42384983 0.87207982]]]


In [11]:
# =========================================
# 11. Create a 10x10 array with random values and find the minimum and maximum values.
# =========================================
print("\n11번")
arr = np.random.random((10,10))
print(arr.min(), arr.max())


11번
0.011190374763754618 0.9938838536212887


In [12]:
# =========================================
# 12. Create a random vector of size 30 and find the mean value.
# =========================================
print("\n12번")
arr = np.random.random(30)
print(arr.mean())


12번
0.5815916733952222


In [13]:
# =========================================
# 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)
# =========================================
print("\n13번")
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)


13번
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
# =========================================
# 14. Add a border filled with 0's around an existing array
# =========================================
print("\n14번")

# before
arr = np.ones((5,5))
print("before")
print(arr)

# after
arr[1:-1,1:-1] = 1
arr[0,:] = 0
arr[-1,:] = 0
arr[:,0] = 0
arr[:,-1] = 0

print("\nafter")
print(arr)


14번
before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

after
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# =========================================
# 15. Expression results with explanation
# =========================================
print("\n15번")

print(0 * np.nan)
# nan : NaN이 포함된 연산 결과는 대부분 NaN이 됨

print(np.nan == np.nan)
# False : NaN은 자기 자신과도 같지 않다고 정의됨

print(np.inf > np.nan)
# False : NaN이 포함된 비교 연산은 항상 False

print(np.nan - np.nan)
# nan : NaN 연산 결과는 NaN

print(np.nan in set([np.nan]))
# True : set 안에 동일한 객체 NaN이 존재하므로 True

print(0.3 == 3 * 0.1)
# False : 부동소수점 정밀도 문제


15번
nan
False
False
nan
True
False


In [16]:
# =========================================
# 16. Normalize a 5x5 random matrix
# =========================================
print("\n16번")

arr = np.random.random((5,5))
normalized = (arr - arr.mean()) / arr.std()
print(normalized)


16번
[[ 1.49886994 -0.88984376  1.35223487  0.00526789  1.30593195]
 [ 0.36130256  0.48751469 -1.55238651  0.51677648  0.02783125]
 [-0.45701555 -0.9697829   0.95511983  0.06586505  0.37791685]
 [ 0.57820807 -0.28322334 -0.83017881 -2.0307273   1.05406755]
 [-1.2840839  -1.96308435  0.10123604  0.99284109  0.57934232]]


In [17]:
# =========================================
# 17. Multiply a 5x3 matrix by a 3x2 matrix
# =========================================
print("\n17번")

A = np.ones((5,3))
B = np.ones((3,2))

print(np.dot(A,B))


17번
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [18]:
# =========================================
# 18. Expression results with explanation
# =========================================
print("\n18번")

print(np.array(0) / np.array(0))
# nan : 0/0 은 정의되지 않아 NaN

print(np.array(0) // np.array(0))
# 0 : 정수 floor division에서는 0으로 처리됨 (warning 발생 가능)

print(np.array([np.nan]).astype(int).astype(float))
# 매우 큰 음수값으로 변환됨 : NaN을 int로 캐스팅할 때 표현 가능한 최소 정수로 변환됨



18번
nan
0
[-9.22337204e+18]


/tmp/ipykernel_331/1961755460.py:6: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_331/1961755460.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_331/1961755460.py:12: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [19]:
# =========================================
# 19. Create a 5x5 matrix with row values ranging from 0 to 4
# =========================================
print("\n19번")

arr = np.tile(np.arange(5), (5,1))
print(arr.astype(float))



19번
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [20]:
# =========================================
# 20. Create a random vector of size 10 and sort it
# =========================================
print("\n20번")

arr = np.random.random(10)
arr.sort()
print(arr)


20번
[0.07400342 0.08307047 0.1922868  0.53439969 0.58906169 0.70468182
 0.76423566 0.79010118 0.97304486 0.99184229]
